coverage:
  ignore:
    - "**/docs.go"
    - "**/middleware.go"
    - "**/users.go"
    - "**/delete-user.go"

  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: true
comment:
  layout: "reach, diff, flags, files"
  behavior: default