version: "3.9"

services:
  frontend:
    build:
      context: ./visual-compiler/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./visual-compiler/frontend:/visual-compiler-frontend
      - /visual-compiler-frontend/node_modules
    command: npm run dev -- --host

  backend:
    build: 
      context: ./visual-compiler/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./visual-compiler/backend:/visual-compiler-backend
    environment:
      - Mongo_username=username
      - Mongo_password=password
      - Mongo_URL=mongodb+srv://%s:%s@visualcompiler.ip4jaot.mongodb.net/?retryWrites=true&w=majority&appName=VisualCompiler
    command: go run main.go