version: "3.9"

services:
  frontend:
    image: vc-frontend:latest
    ports:
      - "3000:3000"
    mem_limit: 256m
    cpus: 0.5

  backend:
    image: vc-backend:latest
    env_file:
      - backend.env
    ports:
      - "8080:8080"
    mem_limit: 256m
    cpus: 0.5
    volumes:
      - ./visual-compiler/backend/.env:/visual-compiler-backend/backend.env:ro
    restart: unless-stopped