version: "3.9"

services:
  frontend:
    build:
      context: ./visual-compiler/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./visual-compiler/frontend:/visual-compiler-frontend
      - /visual-compiler-frontend/node_modules
    command: npm run dev -- --host

  backend:
    build: 
      context: ./visual-compiler/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./visual-compiler/backend:/visual-compiler-backend
      - ./visual-compiler/backend/.env:/visual-compiler-backend/.env
    env_file:
      - ./visual-compiler/backend/.env
    command: go run main.go