version: "3.9"

services:
  frontend:
    build:
      context: ./visual-compiler/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    mem_limit: 256m
    cpus: 0.5

  backend:
    build: 
      context: ./visual-compiler/backend
      dockerfile: Dockerfile
    env_file:
      - backend.env
    ports:
      - "8080:8080"
    mem_limit: 256m
    cpus: 0.5
    volumes:
      - ./visual-compiler/backend/.env:/visual-compiler-backend/backend.env:ro
    environment:
      - Mongo_username
      - Mongo_password
      - Mongo_URI
      - AUTH0_DOMAIN
      - CLIENT_ID
      - CLIENT_SECRET
      - CUSTOM_API
      - OPENAI_API_KEY