version: "3.9"

services:
  frontend:
    build:
      context: ./visual-compiler/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    mem_limit: 256m
    cpus: 0.5
    volumes:
      - ./visual-compiler/frontend:/visual-compiler-frontend
      - /visual-compiler-frontend/node_modules
    command: npm run dev -- --host

  backend:
    build: 
      context: ./visual-compiler/backend
      dockerfile: Dockerfile
    env_file:
      - ./visual-compiler/backend/.env
    ports:
      - "8080:8080"
    mem_limit: 256m
    cpus: 0.5
    volumes:
      - ./visual-compiler/backend/.env:/visual-compiler-backend/.env:ro
    environment:
      - Mongo_username
      - Mongo_password
      - Mongo_URI
    command: ./backend